name: Build .NET MAUI Windows

on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
   
permissions:
  checks: write
  contents: write
  
jobs:
  buildMaui:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Get Version
        id: version
        run: |
          $version = Select-Xml -Path "./src/MauiPaletteCreator/MauiPaletteCreator.csproj" -XPath "//ApplicationDisplayVersion" | Select-Object -ExpandProperty Node | Select-Object -ExpandProperty '#text'
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Publish Windows App
        run: dotnet publish -f net8.0-windows10.0.19041.0 -c Release 
        working-directory: ./src/MauiPaletteCreator
            
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-${{ steps.version.outputs.VERSION }}
          path: |
            **\*.msix

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Windows-${{ steps.version.outputs.VERSION }}
          path: ./release-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          files: "${{github.workspace}}/artifacts/Windows-${{ steps.version.outputs.VERSION }}.zip"
          tag_name: v${{ steps.version.outputs.VERSION }}
          name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
